import { parseUnifiedDiff } from './parse_unified_diff';
import { applyPatch } from './apply_patch';
import { diff } from './diff';
import { Patch, PatchApplyRequest, TextPair, UnifiedDiffText } from '../gen/messages_pb';
import { ctx, CORPUS } from './testkit';
import { MAX_CHARS, MAX_LINES } from './lib';

function parse(text: string): Patch {
  const input = new UnifiedDiffText();
  input.setUnifiedDiff(text);
  return parseUnifiedDiff(ctx, input);
}

function makeDiff(original: string, revised: string): Patch {
  const input = new TextPair();
  input.setOriginal(original);
  input.setRevised(revised);
  return diff(ctx, input);
}

describe('ParseUnifiedDiff', () => {
  it('GOLDEN: parses a hand-written `diff -u` document', () => {
    // Not generated by this package — hand-written in the format GNU diff emits.
    const out = parse(
      ['--- a/app.txt', '+++ b/app.txt', '@@ -1,5 +1,5 @@', ' line1', ' line2', '-line3', '+CHANGED', ' line4', ' line5', ''].join('\n'),
    );
    expect(out.getError()).toBe('');
    expect(out.getIdentical()).toBe(false);
    expect(out.getOriginalName()).toBe('a/app.txt');
    expect(out.getRevisedName()).toBe('b/app.txt');

    const hunks = out.getHunksList();
    expect(hunks).toHaveLength(1);
    expect(hunks[0].getOldStart()).toBe(1);
    expect(hunks[0].getOldLines()).toBe(5);
    expect(hunks[0].getLinesList()).toEqual([' line1', ' line2', '-line3', '+CHANGED', ' line4', ' line5']);
  });

  it('CROSS-NODE: Diff -> ParseUnifiedDiff -> ApplyPatch reproduces the revised text', () => {
    for (const [original, revised] of CORPUS) {
      const label = JSON.stringify([original, revised]);
      const generated = makeDiff(original, revised);
      if (generated.getIdentical()) continue;

      const reparsed = parse(generated.getUnifiedDiff());
      expect([label, reparsed.getError()]).toEqual([label, '']);

      // The reparsed hunks must match the ones Diff emitted.
      expect([label, reparsed.getHunksList().map((h) => h.getLinesList())]).toEqual([
        label,
        generated.getHunksList().map((h) => h.getLinesList()),
      ]);

      const req = new PatchApplyRequest();
      req.setOriginal(original);
      req.setPatch(reparsed);
      const applied = applyPatch(ctx, req);
      expect([label, applied.getApplied(), applied.getError()]).toEqual([label, true, '']);
      expect([label, applied.getText()]).toEqual([label, revised]);
    }
  });

  it('echoes the input diff back on the envelope', () => {
    const text = ['--- original', '+++ revised', '@@ -1,1 +1,1 @@', '-a', '+b', ''].join('\n');
    expect(parse(text).getUnifiedDiff()).toBe(text);
  });

  it('parses empty input as an empty patch', () => {
    for (const empty of ['', '   ', '\n\n']) {
      const out = parse(empty);
      expect(out.getError()).toBe('');
      expect(out.getIdentical()).toBe(true);
      expect(out.getHunksList()).toHaveLength(0);
    }
  });

  it('defaults header names when the diff carries none', () => {
    const out = parse('@@ -1,1 +1,1 @@\n-a\n+b\n');
    expect(out.getError()).toBe('');
    expect(out.getOriginalName()).toBe('original');
    expect(out.getRevisedName()).toBe('revised');
  });

  it('ERROR PATH: rejects prose instead of silently reporting "no changes"', () => {
    // jsdiff parses this to a zero-hunk patch, which would read as "identical".
    // Reporting no changes for a diff the caller believed was real is the
    // dangerous failure this guard exists to prevent.
    const out = parse('Here is my change: I replaced line3 with CHANGED. Hope that helps!');
    expect(out.getError()).toContain('not in unified-diff format');
    expect(out.getIdentical()).toBe(false);
    expect(out.getHunksList()).toHaveLength(0);
  });

  it('ERROR PATH: rejects a malformed @@ header rather than emitting a null-numbered hunk', () => {
    for (const bad of ['@@ nonsense @@\n-a\n+b\n', '@@ -x,y +z,w @@\n-a\n+b\n']) {
      const out = parse(bad);
      expect(out.getError()).not.toBe('');
      expect(out.getHunksList()).toHaveLength(0);
    }
  });

  it('ERROR PATH: rejects a multi-file diff, which this envelope cannot represent', () => {
    const two =
      makeDiff('a\nb\nc\nd', 'a\nX\nc\nd').getUnifiedDiff() +
      makeDiff('p\nq\nr\ns', 'p\nY\nr\ns').getUnifiedDiff();
    const out = parse(two);
    expect(out.getError()).toContain('describes 2 files');
    expect(out.getHunksList()).toHaveLength(0);
  });

  it('BOUNDS: rejects an oversized diff document', () => {
    expect(parse('x'.repeat(MAX_CHARS + 1)).getError()).toContain(
      `unified_diff exceeds the maximum of ${MAX_CHARS} characters`,
    );
    const overLines = Array.from({ length: MAX_LINES + 1 }, () => 'a').join('\n');
    expect(parse(overLines).getError()).toContain(
      `unified_diff exceeds the maximum of ${MAX_LINES} lines`,
    );
  });

  it('is deterministic across repeated invocations', () => {
    const text = ['--- original', '+++ revised', '@@ -1,1 +1,1 @@', '-a', '+b', ''].join('\n');
    const first = parse(text).getHunksList().map((h) => h.getLinesList());
    for (let i = 0; i < 5; i++) {
      expect(parse(text).getHunksList().map((h) => h.getLinesList())).toEqual(first);
    }
  });
});
